version: "3"
services:
  api:
    build: ./hotel-api
    ports:
      - "4200:4200"
    depends_on:
      - mongodb
    container_name: api
  client:
    build: ./hotel-client
    ports:
      - "80:3000"
    depends_on:
      - api
    container_name: client
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: database
